### ISSUE TITLE
Foundations courses sum up to more than 36 ECTS

### ISSUE THREAD

**Issue by teriolx** [Emile-Jn/curriculum-planner#1]
# Description
When selecting all the `Foundations` courses, the summary shows  40.5 / 36 ECTS for the `Foundations courses` and  6 / 4.5 ECTS for `Free electives`. Shown in the screenshot below
![image](https://github.com/user-attachments/assets/7abab30d-aebc-4657-b940-9d59076b27df)

# Steps to reproduce
Import the [chosen_courses.json](https://github.com/user-attachments/files/17687376/chosen_courses.json), which was previously exported by manually selecting all the foundations courses.

# Expected behavior
The `Foundations courses` should be completed and display  36 / 36 ECTS, whereas `Free electives` should not be marked as completed and show 0 / 4.5 ECTS.

# Device details
using Windows 11, reproduced the issue using both Mozilla Firefox 132.0.1 and Google Chrome 130.0.6723.117 browsers

**Comment by Emile-Jn** [comment]
Thanks for reporting this bug, it seems that the bug with 40.5 ECTS in foundations is due to using an old format for the JSON import file, and the bug with free electives is due to ADBS being accidentally in BDHPC/EX in the tsv file. Both issues should be fixed.
