### ISSUE TITLE
Advanced Database System appears multiple times 

### ISSUE THREAD

**Issue by EderChri** [Emile-Jn/curriculum-planner#2]
# Description 
When adding a course to the summer semester, the course "Advanced Database Systems" in the module "BDHPC/EX" shows up multiple times. 
![image](https://github.com/user-attachments/assets/5631a3dc-cc4d-466a-b18f-fa60de60127d)

# Steps to reproduce

1. Create a summer semester
2. Click "Add course"
3. The course  "Advanced Database Systems" shows up at least two times, have had it up to 6 times

# Device Details
Issue occurs both on Firefox 132.0.1 (64-bit) and Microsoft Edge Version 130.0.2849.68 (Official build) (64-bit) on Windows 11

**Comment by Emile-Jn** [comment]
Thanks for reporting this bug!
I have no idea why for now, but ADBS somehow ended up as an extension in the curriculum.tsv file. I manually removed it and it seems ok now, hopefully also fixes it for you. Please delete all variables from your local storage and then see if you still have the same problem or not.
